openapi: 3.1.0
info:
  title: Market Metrics
  version: '2'
servers:
  - url: https://api.amberdata.com/market/metrics
security:
  - sec0: []
paths:
  /{asset}/supply/latest:
    get:
      summary: Latest
      description: >-
        Retrieves latest supply data for blockchains and tokens.***Note**: We
        get supply values directly from our data/nodes. Blockchains included in
        our supply data are: Ethereum, Bitcoin and Litecoin.
      operationId: market-metrics-asset-supply-latest
      parameters:
        - name: asset
          in: path
          description: >-
            The symbol of the asset or token. <BR>**[Example]** BTC, ETH, MATIC,
            etc.
          schema:
            type: string
            default: btc
          required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      timestamp: '2021-01-26T16:25:49.000Z'
                      issuance: '6.25'
                      totalSupply: '18611089.79497096'
                      circulatingSupply: '18611056'
                      maxSupply: '21000000'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        example: '2021-01-26T16:25:49.000Z'
                      issuance:
                        type: string
                        example: '6.25'
                      totalSupply:
                        type: string
                        example: '18611089.79497096'
                      circulatingSupply:
                        type: string
                        example: '18611056'
                      maxSupply:
                        type: string
                        example: '21000000'
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
  /{asset}/supply/historical:
    get:
      summary: Historical
      description: >-
        Retrieves historical supply data for blockchains and tokens from October
        2019 forward. ***Note**: We get supply values directly from our
        data/nodes. Blockchains included in our supply data are: Ethereum,
        Bitcoin and Litecoin.
      operationId: market-metrics-asset-supply-historical
      parameters:
        - name: asset
          in: path
          description: >-
            The symbol of the asset or token. <BR>**[Example]** BTC, ETH, MATIC,
            etc.
          schema:
            type: string
            default: btc
          required: true
        - name: startDate
          in: query
          description: >-
            Returns data after this date. Accepts ISO8601 and Epoch/Unix
            timestamps
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          description: >-
            Returns data before this date. Accepts ISO8601 and Epoch/Unix
            timestamps
          schema:
            type: string
            format: date-time
        - name: timeFormat
          in: query
          description: >-
            **[Optional]** Time format of the timestamps in the return
            payload.<BR/>**[Defaults]** `milliseconds | ms* | iso | iso8601 | hr
            | human_readable`
          schema:
            type: string
            default: iso
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        startDate: '2021-01-22T00:00:00.000Z'
                        endDate: '2021-01-26T16:42:50.026Z'
                      data:
                        - timestamp: '2021-01-22T00:00:00.000Z'
                          issuance: '6.25'
                          totalSupply: '18607677.29497096'
                          circulatingSupply: '18607618'
                          maxSupply: '21000000'
                        - timestamp: '2021-01-23T00:00:00.000Z'
                          issuance: '6.25'
                          totalSupply: '18608652.29497096'
                          circulatingSupply: '18608487'
                          maxSupply: '21000000'
                        - timestamp: '2021-01-24T00:00:00.000Z'
                          issuance: '6.25'
                          totalSupply: '18609521.04497096'
                          circulatingSupply: '18609437'
                          maxSupply: '21000000'
                        - timestamp: '2021-01-25T00:00:00.000Z'
                          issuance: '6.25'
                          totalSupply: '18610396.04497096'
                          circulatingSupply: '18610293'
                          maxSupply: '21000000'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          startDate:
                            type: string
                            example: '2021-01-22T00:00:00.000Z'
                          endDate:
                            type: string
                            example: '2021-01-26T16:42:50.026Z'
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            timestamp:
                              type: string
                              example: '2021-01-22T00:00:00.000Z'
                            issuance:
                              type: string
                              example: '6.25'
                            totalSupply:
                              type: string
                              example: '18607677.29497096'
                            circulatingSupply:
                              type: string
                              example: '18607618'
                            maxSupply:
                              type: string
                              example: '21000000'
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
  /exchanges/{exchange}/assets/volumes/historical:
    get:
      summary: Asset Volume Historical
      description: |-
        Retrieves the daily volume of assets on each exchange.

        ***Note**: This endpoint excludes data from LMAX.
      operationId: market-metrics-exchanges-assets-volumes-historical
      parameters:
        - name: exchange
          in: path
          description: The exchange for which to retrieve the requested data.
          schema:
            type: string
            default: gdax
          required: true
        - name: asset
          in: query
          description: >-
            **[Optional]** The asset for which to retrieve the most current
            data.<BR/>**[Default]** All available assets.
          schema:
            type: string
            default: btc
        - name: quoteVolume
          in: query
          description: '**[Optional]** Aggregate on quote volume instead of base volume.'
          schema:
            type: boolean
            default: false
        - name: direction
          in: query
          description: >-
            **[Optional]** The order in which to return the results, ordered by
            volumeUSD (ascending or descending). By default, records are
            returned in descending order, so the records with the largest volume
            are returned first.
          schema:
            type: string
            default: desc
        - name: startDate
          in: query
          description: >-
            **[Optional]** Payload only includes data after this date
            (inclusive).<BR>**[Formats]** `seconds | milliseconds |
            iso8601`<BR>**[Examples]** `1578531600 | 1578531600000 |
            2020-09-01T01:00:00`
          schema:
            type: string
        - name: endDate
          in: query
          description: >-
            **[Optional]** Payload only includes data before this date
            (exclusive).<BR>**[Formats]** `seconds | milliseconds |
            iso8601`<BR>**[Examples]** `1578531600 | 1578531600000 |
            2020-09-01T01:00:00`
          schema:
            type: string
        - name: timeFormat
          in: query
          description: >-
            **[Optional]** Time format of the timestamps in the return
            payload.<BR/>**[Defaults]** `milliseconds | ms* | iso | iso8601 | hr
            | human_readable`
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        startDate: 2022-03-10 00:00:00 000
                        endDate: 2022-03-11 10:00:00 000
                      data:
                        - exchange: gdax
                          asset: btc
                          timestamp: 2022-03-10 00:00:00 000
                          volumeUSD: '1029206608.30715038'
                        - exchange: gdax
                          asset: btc
                          timestamp: 2022-03-11 00:00:00 000
                          volumeUSD: '767275182.09255630'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          startDate:
                            type: string
                            example: 2022-03-10 00:00:00 000
                          endDate:
                            type: string
                            example: 2022-03-11 10:00:00 000
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            exchange:
                              type: string
                              example: gdax
                            asset:
                              type: string
                              example: btc
                            timestamp:
                              type: string
                              example: 2022-03-10 00:00:00 000
                            volumeUSD:
                              type: string
                              example: '1029206608.30715038'
      deprecated: false
  /exchanges/{exchange}/pairs/volumes/historical:
    get:
      summary: Pair Volume Historical
      description: Retrieves the daily volume of pairs on each exchange.
      operationId: market-metrics-exchanges-pairs-volumes-historical
      parameters:
        - name: exchange
          in: path
          description: The exchange for which to retrieve the requested data.
          schema:
            type: string
            default: gdax
          required: true
        - name: pair
          in: query
          description: >-
            **[Optional]** The pair for which to retrieve the most current
            data.<BR/>**[Default]** All available pairs.
          schema:
            type: string
            default: btc_usd
        - name: direction
          in: query
          description: >-
            **[Optional]** The order in which to return the results, ordered by
            volumeUSD (ascending or descending). By default, records are
            returned in descending order, so the records with the largest volume
            are returned first.
          schema:
            type: string
            default: desc
        - name: startDate
          in: query
          description: >-
            **[Optional]** Payload only includes data after this date
            (inclusive).<BR>**[Formats]** `seconds | milliseconds |
            iso8601`<BR>**[Examples]** `1578531600 | 1578531600000 |
            2020-09-01T01:00:00`
          schema:
            type: string
        - name: endDate
          in: query
          description: >-
            **[Optional]** Payload only includes data before this date
            (exclusive).<BR>**[Formats]** `seconds | milliseconds |
            iso8601`<BR>**[Examples]** `1578531600 | 1578531600000 |
            2020-09-01T01:00:00`
          schema:
            type: string
        - name: timeFormat
          in: query
          description: >-
            **[Optional]** Time format of the timestamps in the return
            payload.<BR/>**[Defaults]** `milliseconds | ms* | iso | iso8601 | hr
            | human_readable`
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        startDate: 2022-03-10 00:00:00 000
                        endDate: 2022-03-11 10:00:00 000
                      data:
                        - exchange: gdax
                          pair: btc_usd
                          timestamp: 2022-03-10 00:00:00 000
                          volumeUSD: '820976607.01839280'
                        - exchange: gdax
                          pair: btc_usd
                          timestamp: 2022-03-11 00:00:00 000
                          volumeUSD: '616422583.44034633'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          startDate:
                            type: string
                            example: 2022-03-10 00:00:00 000
                          endDate:
                            type: string
                            example: 2022-03-11 10:00:00 000
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            exchange:
                              type: string
                              example: gdax
                            pair:
                              type: string
                              example: btc_usd
                            timestamp:
                              type: string
                              example: 2022-03-10 00:00:00 000
                            volumeUSD:
                              type: string
                              example: '820976607.01839280'
      deprecated: false
  /exchanges/{exchange}/pairs/volumes/latest:
    get:
      summary: Pair Volume Latest
      description: >-
        Retrieves the daily volume of pairs on each exchange over a rolling 24h
        period, updated hourly. The timestamp returned represents the beginning
        of the daily bar, following the same approach as OHLCV.
      operationId: market-metrics-exchanges-pairs-volumes-latest
      parameters:
        - name: exchange
          in: path
          description: The exchange for which to retrieve the requested data.
          schema:
            type: string
            default: gdax
          required: true
        - name: pair
          in: query
          description: >-
            **[Optional]** The pair for which to retrieve the most current data
            (ie. btc_usd, eth_usd, etc.).<BR/>**[Default]** All available pairs.
          schema:
            type: string
        - name: direction
          in: query
          description: >-
            **[Optional]** The order in which to return the results, ordered by
            volumeUSD (ascending or descending). By default, records are
            returned in descending order, so the records with the largest volume
            are returned first.
          schema:
            type: string
            default: desc
        - name: timeFormat
          in: query
          description: >-
            **[Optional]** Time format of the timestamps in the return
            payload.<BR/>**[Defaults]** `milliseconds | ms* | iso | iso8601 | hr
            | human_readable`
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      data:
                        - exchange: gdax
                          pair: btc_usd
                          timestamp: 2022-03-13 14:00:00 000
                          volumeUSD: '417084146.60114834'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            exchange:
                              type: string
                              example: gdax
                            pair:
                              type: string
                              example: btc_usd
                            timestamp:
                              type: string
                              example: 2022-03-13 14:00:00 000
                            volumeUSD:
                              type: string
                              example: '417084146.60114834'
      deprecated: false
  /exchanges/{exchange}/assets/volumes/latest:
    get:
      summary: Asset Volume Latest
      description: >-
        Retrieves the daily volume of assets on each exchange over a rolling 24h
        period, updated hourly. The timestamp returned represents the beginning
        of the daily bar, following the same approach as OHLCV. **Note**: This
        endpoint excludes data from LMAX.
      operationId: market-metrics-exchanges-assets-volumes-latest
      parameters:
        - name: exchange
          in: path
          description: The exchange for which to retrieve the requested data.
          schema:
            type: string
            default: gdax
          required: true
        - name: asset
          in: query
          description: >-
            **[Optional]** The asset for which to retrieve the most current data
            (ie. btc, eth, etc.)<BR/>**[Default]** All available assets.
          schema:
            type: string
        - name: quoteVolume
          in: query
          description: '**[Optional]** Aggregate on quote volume instead of base volume.'
          schema:
            type: boolean
            default: false
        - name: direction
          in: query
          description: >-
            **[Optional]** The order in which to return the results, ordered by
            volumeUSD (ascending or descending). By default, records are
            returned in descending order, so the records with the largest volume
            are returned first.
          schema:
            type: string
            default: desc
        - name: timeFormat
          in: query
          description: >-
            **[Optional]** Time format of the timestamps in the return
            payload.<BR/>**[Defaults]** `milliseconds | ms* | iso | iso8601 | hr
            | human_readable`
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      data:
                        - exchange: gdax
                          asset: btc
                          timestamp: 2022-03-13 14:00:00 000
                          volumeUSD: '520426096.98878671'
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            exchange:
                              type: string
                              example: gdax
                            asset:
                              type: string
                              example: btc
                            timestamp:
                              type: string
                              example: 2022-03-13 14:00:00 000
                            volumeUSD:
                              type: string
                              example: '520426096.98878671'
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: apiKey
      in: header
      x-default: API-KEY
      name: x-api-key
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
x-readme-fauxas: true
