openapi: 3.1.0
info:
  title: Asset Reference & Classification API
  version: '2'
servers:
  - url: https://api.amberdata.com/arc
security:
  - sec0: []
paths:
  /updates:
    get:
      summary: Updates
      description: Retrieve the **latest** updates of assets and instruments added to ARC.
      operationId: asset-reference-classifications-list-updates
      parameters:
        - name: groupBy
          in: query
          schema:
            type: string
            enum:
              - assets
              - instruments
            default: assets
        - name: timeFormat
          in: query
          description: >-
            Represent timestamps in epoch milliseconds or human readable ISO
            format.
          schema:
            type: string
            enum:
              - iso8601
        - name: updatesSince
          in: query
          description: >-
            Look back cutoff for updates made to the ARC dataset, represented in
            ISO format.<br><br>`P1D` represents 24 hrs (1 day) and `P7D`
            represents 7 days.
          schema:
            type: string
            enum:
              - P1D
              - P7D
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                groupBy=instruments:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        next: null
                      data:
                        updateType: instruments
                        updates:
                          - arcInstrumentId: AMB:GRA000000002_AMB:USD000000335
                            arcInstrument: grass_usdt
                            baseAssetSymbol: grass
                            nativeInstrument: GRASSUSDT
                            exchange: bitget
                            assetName: Grass
                            assetArcId: AMB:GRA000000002
                            quoteArcId: AMB:USD000000335
                            instrumentType: spot
                          - arcInstrumentId: AMB:GRA000000002_AMB:USD000000335
                            arcInstrument: grass_usdt
                            baseAssetSymbol: grass
                            nativeInstrument: GRASSUSDT
                            exchange: bybit
                            assetName: Grass
                            assetArcId: AMB:GRA000000002
                            quoteArcId: AMB:USD000000335
                            instrumentType: spot
                          - arcInstrumentId: AMB:GRA000000002_AMB:USD000000335
                            arcInstrument: grass_usdt
                            baseAssetSymbol: grass
                            nativeInstrument: GRASS/USDT
                            exchange: huobi
                            assetName: Grass
                            assetArcId: AMB:GRA000000002
                            quoteArcId: AMB:USD000000335
                            instrumentType: spot
                          - arcInstrumentId: AMB:GRA000000002_AMB:USD000000335
                            arcInstrument: grass_usdt
                            baseAssetSymbol: grass
                            nativeInstrument: GRASSUSDT
                            exchange: mexc
                            assetName: Grass
                            assetArcId: AMB:GRA000000002
                            quoteArcId: AMB:USD000000335
                            instrumentType: spot
                          - arcInstrumentId: AMB:GRA000000002_AMB:USD000000335
                            arcInstrument: grass_usdt
                            baseAssetSymbol: grass
                            nativeInstrument: GRASS_USDT
                            exchange: poloniex
                            assetName: Grass
                            assetArcId: AMB:GRA000000002
                            quoteArcId: AMB:USD000000335
                            instrumentType: spot
                groupBy=assets:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        next: null
                      data:
                        updateType: assets
                        updates:
                          - assetSymbol: grass
              schema:
                oneOf:
                  - title: groupBy=instruments
                    type: object
                    properties:
                      status:
                        type: integer
                        example: 200
                        default: 0
                      title:
                        type: string
                        example: OK
                      description:
                        type: string
                        example: Successful request
                      payload:
                        type: object
                        properties:
                          metadata:
                            type: object
                            properties:
                              next: {}
                          data:
                            type: object
                            properties:
                              updateType:
                                type: string
                                example: instruments
                              updates:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    arcInstrumentId:
                                      type: string
                                      example: AMB:GRA000000002_AMB:USD000000335
                                    arcInstrument:
                                      type: string
                                      example: grass_usdt
                                    baseAssetSymbol:
                                      type: string
                                      example: grass
                                    nativeInstrument:
                                      type: string
                                      example: GRASSUSDT
                                    exchange:
                                      type: string
                                      example: bitget
                                    assetName:
                                      type: string
                                      example: Grass
                                    assetArcId:
                                      type: string
                                      example: AMB:GRA000000002
                                    quoteArcId:
                                      type: string
                                      example: AMB:USD000000335
                                    instrumentType:
                                      type: string
                                      example: spot
                  - title: groupBy=assets
                    type: object
                    properties:
                      status:
                        type: integer
                        example: 200
                        default: 0
                      title:
                        type: string
                        example: OK
                      description:
                        type: string
                        example: Successful request
                      payload:
                        type: object
                        properties:
                          metadata:
                            type: object
                            properties:
                              next: {}
                          data:
                            type: object
                            properties:
                              updateType:
                                type: string
                                example: assets
                              updates:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    assetSymbol:
                                      type: string
                                      example: grass
      deprecated: false
  /classifications:
    get:
      summary: List Classifications
      description: Retrieve the **latest** known classifications for assets in ARC.
      operationId: asset-reference-classification-list-classifications
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        next: null
                      data:
                        - tagName: Proof-of-Work
                          tagDescription: >-
                            Assets that require validation of block transactions
                            where miners are solving computationally expensive
                            cryptographic problems
                        - tagName: Proof-of-Stake
                          tagDescription: >-
                            Assets that require validation of block transactions
                            by participants who offer their holdings of said
                            asset as collateral to validate transactions
                        - tagName: Stablecoin
                          tagDescription: >-
                            Assets that are intended to offer participants in
                            the digital asset ecosystem access to blockchain
                            applications and decentralized protocols without
                            being exposed to volatile price action in digitally
                            native tokens
                        - tagName: Real World Asset
                          tagDescription: >-
                            Assets that are an on-chain tokenized representation
                            of off-chain assets and are pegged to the
                            performance of the underlying off-chain asset
                        - tagName: Machine Learning & AI
                          tagDescription: >-
                            Assets native to protocols that facilitate model
                            training, inference, predictions, and generative
                            artificial intelligence
                        - tagName: Gaming
                          tagDescription: >-
                            Assets native to applications for blockchain-based
                            gaming and their communities. Decentralized gaming
                            applications often include a native token to
                            incentivize players with monetary rewards based on
                            their participation and success in the game
                        - tagName: Metaverse
                          tagDescription: >-
                            Assets native to applications and protocols
                            associated with a loose network of virtual worlds
                            where social connections and interactions are the
                            primary function
                        - tagName: Advertising
                          tagDescription: >-
                            Assets native to applications that facilitate the
                            tokenization of impressions for interacting with ads
                            and marketing campaigns. These tokens correspond
                            with the user's viewership whereby they are rewarded
                            in the token for their time and attention
                        - tagName: Content & Streaming
                          tagDescription: >-
                            Assets native to applications that support the
                            creation and broadcasting of creative content, such
                            as video, music, or art, and enable social
                            interactions between users and communities. The
                            networks are powered by the asset, allowing creators
                            to communicate and distribute content autonomously
                        - tagName: Staking
                          tagDescription: >-
                            Assets native to decentralized applications that
                            provide the user with yield for locking up their
                            asset(s) to participate in the validation and
                            securing of block transactions
                        - tagName: Derivatives
                          tagDescription: >-
                            Assets native to the operations of an application
                            that facilitates the creation and transfer of
                            derivatives (futures and options etc.) and synthetic
                            assets. These assets are not derivatives themselves
                            but rather enable trading access and liquidity to a
                            derivative/synthetic product that is uniquely
                            offered and distributed by the protocol
                        - tagName: Liquidity Providers
                          tagDescription: >-
                            Assets that represent a share of a user's liquidity
                            relative to other participants in a liquidity pool.
                            Liquidity Pool, or LP, tokens allow holders to
                            control their share of the underlying pool. These
                            tokens can be redeemed for the underlying shares,
                            exchanged and even used in other applications
                        - tagName: Prediction Market
                          tagDescription: >-
                            Assets native to decentralized applications that are
                            used for speculative trading based on the outcome of
                            future events. Prediction market protocols typically
                            allow users to place bets on probabilities of
                            certain events occurring
                        - tagName: Yield
                          tagDescription: >-
                            Assets native to applications where the primary goal
                            is to generate interest income for users
                        - tagName: Lending
                          tagDescription: >-
                            Assets native to the operations of an automated
                            market maker that primarily provides lending and
                            borrowing services, enabling peer-to-peer loans via
                            liquidity pools. Decentralized lending applications
                            allow users to borrow or lend against other assets,
                            while the other side of the transaction is held and
                            collateralized by the native asset of the lending
                            protocol or other assets in the liquidity pool
                        - tagName: DEX
                          tagDescription: >-
                            Assets native to the operations of an automated
                            market maker for decentralized spot markets,
                            enabling the peer-to-peer transfer of assets through
                            liquidity pools
                        - tagName: Smart Contract
                          tagDescription: >-
                            Assets native to applications or blockchains that
                            allow automatic execution of an agreement between
                            two parties, when the conditions stipulated in the
                            agreement are met. Smart contracts can be
                            standardized or custom computer code that is
                            deployed to the application or network
                        - tagName: Blockchain Infrastructure
                          tagDescription: >-
                            Assets native to applications and ecosystems focused
                            on providing the infrastructure for blockchain
                            networks to scale and be use-case specialized. These
                            infrastructure solutions are colloquially also known
                            as "Layer 0" and can also facilitate
                            interoperability between so-called "app chains"
                        - tagName: Layer-1
                          tagDescription: >-
                            Assets native to a blockchain in which the network
                            can validate and finalize transactions on its own
                            without another chain
                        - tagName: Layer-2
                          tagDescription: >-
                            Assets native to a blockchain scaling solution
                            focused on improving throughput, consistency, and
                            cost incurred to process transactions relative to
                            the underlying, parent blockchain. The scaling
                            solution inherits the security of the parent
                            blockchain, colloquially known as "Layer 1" and
                            transactions must still be validated on the parent
                            chain
                        - tagName: Governance
                          tagDescription: >-
                            Assets utilized to collaborate, vote and execute
                            proposals that affect the operations of the
                            applications or user activity
                        - tagName: Oracles
                          tagDescription: >-
                            Assets native to applications that deliver off-chain
                            data to enrich on-chain use cases and products
                        - tagName: Privacy
                          tagDescription: >-
                            Assets native to applications or networks that offer
                            privacy enhancements to facilitate the anonymous
                            transfer of value for on-chain payments. Networks
                            with privacy features can allow users to self-select
                            when their on-chain data will be publicly available,
                            or encrypted as an unidentifiable and untraceable
                            activity
                        - tagName: Meme
                          tagDescription: >-
                            Assets that are based on or derive value from memes,
                            social commentary and community that supports,
                            engages with and transacts on the asset
                        - tagName: Remittance
                          tagDescription: >-
                            Assets utilized for their velocity in the transfer
                            of monetary value domestically and across borders
                            for payments
                        - tagName: Transparent
                          tagDescription: >-
                            Asset whose blockchain network ledger displays the
                            deposit addresses of both senders and receivers and
                            may reveal wallet balances publicly
                        - tagName: DeFi
                          tagDescription: >-
                            Asset native to decentralized applications that
                            provide the user with economic incentives, trading
                            power, or an on-chain alternative to traditional
                            financial services and products. These tokens often
                            serve as the mechanism to engage with its financial
                            application as well as the reward that is used to
                            collateralize or compensate the user for the
                            financial activity that the protocol offers
                        - tagName: DePIN
                          tagDescription: >-
                            Assets native to decentralized applications that
                            enable the sharing, distribution and maintenance of
                            physical infrastructure for a variety of
                            applications including data storage, energy usage,
                            sensors and wireless connectivity
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          next: {}
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            tagName:
                              type: string
                              example: Proof-of-Work
                            tagDescription:
                              type: string
                              example: >-
                                Assets that require validation of block
                                transactions where miners are solving
                                computationally expensive cryptographic problems
      deprecated: false
  /exchanges/statistics:
    get:
      summary: Exchange Statistics
      description: >-
        Retrieve the **latest** known instruments statistics from exchanges that
        Amberdata supports.
      operationId: asset-reference-classification-exchange-statistics
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        next: null
                      data:
                        lastUpdatedAt: 1733246810233
                        totalExchanges: 22
                        totalInstrumentsSpot: 22629
                        byExchange:
                          - exchange: binance
                            instrumentsSpot: 2832
                          - exchange: binanceus
                            instrumentsSpot: 549
                          - exchange: bitfinex
                            instrumentsSpot: 1428
                          - exchange: bitget
                            instrumentsSpot: 991
                          - exchange: bithumb
                            instrumentsSpot: 617
                          - exchange: bitmex
                            instrumentsSpot: 20
                          - exchange: bitstamp
                            instrumentsSpot: 271
                          - exchange: bybit
                            instrumentsSpot: 751
                          - exchange: cboedigital
                            instrumentsSpot: 10
                          - exchange: ftx
                            instrumentsSpot: 621
                          - exchange: ftxus
                            instrumentsSpot: 67
                          - exchange: gdax
                            instrumentsSpot: 721
                          - exchange: gemini
                            instrumentsSpot: 274
                          - exchange: huobi
                            instrumentsSpot: 1905
                          - exchange: itbit
                            instrumentsSpot: 14
                          - exchange: kraken
                            instrumentsSpot: 1350
                          - exchange: lmax
                            instrumentsSpot: 46
                          - exchange: mercadobitcoin
                            instrumentsSpot: 701
                          - exchange: mexc
                            instrumentsSpot: 5853
                          - exchange: okex
                            instrumentsSpot: 1283
                          - exchange: poloniex
                            instrumentsSpot: 1686
                          - exchange: zb
                            instrumentsSpot: 639
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                    default: 0
                  title:
                    type: string
                    example: OK
                  description:
                    type: string
                    example: Successful request
                  payload:
                    type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          next: {}
                      data:
                        type: object
                        properties:
                          lastUpdatedAt:
                            type: integer
                            example: 1733246810233
                            default: 0
                          totalExchanges:
                            type: integer
                            example: 22
                            default: 0
                          totalInstrumentsSpot:
                            type: integer
                            example: 22629
                            default: 0
                          byExchange:
                            type: array
                            items:
                              type: object
                              properties:
                                exchange:
                                  type: string
                                  example: binance
                                instrumentsSpot:
                                  type: integer
                                  example: 2832
                                  default: 0
      deprecated: false
  /search:
    get:
      summary: Search Assets
      description: Filter and identify various assets indexed by ARC.
      operationId: asset-reference-classification-search-assets
      parameters:
        - name: filterBy
          in: query
          schema:
            type: string
            enum:
              - exchange
              - classificationTag
              - assetName
              - assetSymbol
              - assetArcId
        - name: filterValue
          in: query
          description: >-
            An appropriate value that is within the context described by
            `filterBy`. <br><br> **Examples**:
            <br><br>`filterBy=classificationTag&filterValue=Meme`
            <br><br>`filterBy=exchange&filterValue=poloniex`
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status: 200
                    title: OK
                    description: Successful request
                    payload:
                      metadata:
                        next: null
                      data:
                        - assetSymbol: 2024token
                          assetName: 2024TOKEN
                          assetArcId: AMB:202000003171
                          classificationTags:
                            - Meme
                        - assetSymbol: 3d3d
                          assetName: 3D3D
                          assetArcId: AMB:3D3000001344
                          classificationTags:
                            - Meme
                        - assetSymbol: 3w3w
                          assetName: 3w3w
                          assetArcId: AMB:3W3000000000
                          classificationTags:
                            - Meme
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: apiKey
      in: header
      name: x-api-key
      x-default: API_KEY
x-readme:
  headers: []
  explorer-enabled: true
  proxy-enabled: true
x-readme-fauxas: true
